[general]
# delay before starting
# startup_delay = millisecond
startup_delay = 0
# delay between launches
# delay = millisecond
delay = 200
# struct of logs is LOG_INFO, LOG_WARN, LOG_ERR, LOG_DEF
# 0 - info and subsequent, 1 - warnings and subsequent, 2 - errors and subsequent, 3 - only default printings
# log_level = <0|1|2|3>
log_level = 0


[apps]
# name = allow: <0|1>, delay: millisecond
# firefox.desktop = allow: 1, delay: 1000
